REALMC-12116: Bump version to 2.3.5
10gen/realm-cli pull request #276
Opened 2022-03-07 20:51 UTC by mburdette

2022-03-07 21:19 UTC, chickenbug approved these changes

2022-03-07 21:20 UTC, chickenbug requested changes
Wait this would trigger a release. Has QA been completed for this yet?

2022-03-09 16:34 UTC, mburdette commented
> Wait this would trigger a release. Has QA been completed for this yet?

I am aware that this triggers a release and QA hasn't been completed, was just getting the PR ready

2022-03-09 16:37 UTC, chickenbug approved these changes

2022-03-09 16:39 UTC, merged